import { build } from 'esbuild'

await build({
  entryPoints: ['src/index.ts'],
  outfile: 'lib/index.js',
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: true,
  // 宿主提供框架与 harness 包；打进产物会造成两份实例，服务查找失败。
  external: ['@deepseek-ai/*'],
})

// 客户端半部产物形态实测自 dsh-context（~/.dsh/profiles/web/node_modules/
// dsh-context/lib/client.js）：dsh 的客户端模块加载器用惰性 CJS 模型——脚本
// 执行只向 `window.__ModuleLoader__` 登记工厂，模块体的副作用在物化时才跑。
// banner/footer 把 esbuild 的 CJS 产物包进该登记调用；`require` 由加载器注入，
// 解析 `@deepseek-ai/*` 与 `react` 这两个外部化依赖到宿主已提供的同一份实例。
await build({
  entryPoints: ['src/client/index.ts'],
  outfile: 'lib/client.js',
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  sourcemap: true,
  external: ['@deepseek-ai/*', 'react'],
  banner: {
    js: '/* dsh-dev-crew client bundle — generated by scripts/build.mjs from src/client/ */\n'
      + 'window.__ModuleLoader__.load({\n'
      + '  id: "dsh-dev-crew",\n'
      + '  factory: (require) => {\n'
      + '    var module = { exports: {} };\n'
      + '    var exports = module.exports;',
  },
  footer: {
    js: '    return module.exports;\n'
      + '  },\n'
      + '});',
  },
})
